### ISSUE TITLE
ENOENT: no such file or directory, stat 'E:\pinokio\api\photomaker2.git\{{input.event[0]}}'

### ISSUE THREAD

**Issue by konservat0r** [pinokiocomputer/program.pinokio.computer#6]
ENOENT: no such file or directory, stat 'E:\pinokio\api\photomaker2.git\{{input.event[0]}}'

**Comment by sketchycarder** [comment]
Have you found anyway around this, I’m facing the same thing when I’m trying to use comfy ui

**Comment by konservat0r** [comment]
no
